/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stupid.UI;

import Stupid.DAO.StaDAO;
import Stupid.Modal.Customer;
import com.jtattoo.plaf.fast.FastLookAndFeel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A
 */
public class TableJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TableJFrame
     */
    public TableJFrame() {
        initComponents();
        setTitle("THỐNG KÊ");
        thongKeDanhSo();

    }

    public void thongKeDanhSo() {
        StaDAO sDAO = new StaDAO();
        ArrayList<Customer> dsKH = sDAO.loadList();
        int tong = dsKH.size();
        txtTong.setText(tong + "");
        ArrayList<Customer> dsNam = sDAO.loadListGT("NAM");
        int nam = dsNam.size();
        txtNam.setText(nam + "");
        ArrayList<Customer> dsNu = sDAO.loadListGT("NỮ");
        int nu = dsNu.size();
        txtNu.setText(nu + "");
        float sum = 0;
        String makh;
        for (int i = 0; i <= dsKH.size(); i++) {

            makh = "KH00" + i;
            float tienKH = sDAO.tinhTongDanhThu(makh);
            sum = sum + tienKH;

        }
        txtDonPhi.setText(sum + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtTong = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txtNam = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        txtNu = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        txtDonPhi = new javax.swing.JTextField();
        cboNam = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "TỔNG KHÁCH HÀNG :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        txtTong.setEditable(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTong, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "SỐ KH NAM :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        txtNam.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNam, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "SỐ KH NỮ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        txtNu.setEditable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNu, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "TỔNG DANH THU :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        txtDonPhi.setEditable(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDonPhi, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDonPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TẤT CẢ", "2017", "2018", "2019", "2020" }));
        cboNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboNam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamActionPerformed
        // TODO add your handling code here:
        int year = 0;
        Object obj = evt.getSource();
        if (obj == cboNam) {
            String luachon = cboNam.getSelectedItem().toString().trim();
            try{
            year = Integer.parseInt(luachon);
            }catch(Exception ex){
                
            }
            if (luachon == "TẤT CẢ") {
                thongKeDanhSo();
            } else if (luachon == "2018") {
                StaDAO sDAO = new StaDAO();
                ArrayList<Customer> dsKH = sDAO.thongKeTheoNam(year);
                int tong = dsKH.size();
                txtTong.setText(tong + "");
                ArrayList<Customer> dsNam = sDAO.loadListGTtheoNam("NAM", year);
                int nam = dsNam.size();
                txtNam.setText(nam + "");
                ArrayList<Customer> dsNu = sDAO.loadListGTtheoNam("NỮ", year);
                int nu = dsNu.size();
                txtNu.setText(nu + "");
                float sum = 0;
               float tienKH = sDAO.tinhTongDanhThuTheoNam(year);
                
                txtDonPhi.setText(tienKH + "");
            } else if (luachon == "2017") {
                StaDAO sDAO = new StaDAO();
                ArrayList<Customer> dsKH = sDAO.thongKeTheoNam(year);
                int tong = dsKH.size();
                txtTong.setText(tong + "");
                ArrayList<Customer> dsNam = sDAO.loadListGTtheoNam("NAM", year);
                int nam = dsNam.size();
                txtNam.setText(nam + "");
                ArrayList<Customer> dsNu = sDAO.loadListGTtheoNam("NỮ", year);
                int nu = dsNu.size();
                txtNu.setText(nu + "");
                float sum = 0;
                String makh;
               

                    
                    float tienKH = sDAO.tinhTongDanhThuTheoNam(year);
                
                txtDonPhi.setText(tienKH + "");
            } else if (luachon == "2019") {
                StaDAO sDAO = new StaDAO();
                ArrayList<Customer> dsKH = sDAO.thongKeTheoNam(year);
                int tong = dsKH.size();
                txtTong.setText(tong + "");
                ArrayList<Customer> dsNam = sDAO.loadListGTtheoNam("NAM", year);
                int nam = dsNam.size();
                txtNam.setText(nam + "");
                ArrayList<Customer> dsNu = sDAO.loadListGTtheoNam("NỮ", year);
                int nu = dsNu.size();
                txtNu.setText(nu + "");
                float sum = 0;
                float tienKH = sDAO.tinhTongDanhThuTheoNam(year);
                
                txtDonPhi.setText(tienKH + "");
            } else if (luachon == "2020") {
                StaDAO sDAO = new StaDAO();
                ArrayList<Customer> dsKH = sDAO.thongKeTheoNam(year);
                int tong = dsKH.size();
                txtTong.setText(tong + "");
                ArrayList<Customer> dsNam = sDAO.loadListGTtheoNam("NAM", year);
                int nam = dsNam.size();
                txtNam.setText(nam + "");
                ArrayList<Customer> dsNu = sDAO.loadListGTtheoNam("NỮ", year);
                int nu = dsNu.size();
                txtNu.setText(nu + "");
                float sum = 0;
                float tienKH = sDAO.tinhTongDanhThuTheoNam(year);
                
                txtDonPhi.setText(tienKH + "");
            }
        }
    }//GEN-LAST:event_cboNamActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            Properties props = new Properties();
            props.put("logoString", "");
            FastLookAndFeel.setCurrentTheme(props);

            UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
        } catch (Exception ex) {
        }
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtDonPhi;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtNu;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables
}
